spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${YML_SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${YML_MAIL_HOST}
    port: ${YML_MAIL_PORT}
    username: ${YML_MAIL_USERNAME}
    password: ${YML_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true