spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.YML_SPRING_DATASOURCE_URL}
    username: ${secrets.YML_SPRING_DATASOURCE_USERNAME}
    password: ${secrets.YML_SPRING_DATASOURCE_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.YML_MAIL_USERNAME}
    password: ${secrets.YML_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true